// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqvfznlixwpzbvseyuwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxdmZ6bmxpeHdwemJ2c2V5dXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjAxMzQsImV4cCI6MjA3MDYzNjEzNH0.jxpo7aa_vRCKwU4evKqkh9FH8nzG5BQ_5tixcG-h_58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});